<?php

declare(strict_types=1);

namespace WHMCS\Module\Addon\Security_Pack\Security\TwoFactor;

use RobThree\Auth\Algorithm as RobThreeAlgorithm;
use RobThree\Auth\TwoFactorAuth as RobThreeTwoFactorAuth;

if(!defined("WHMCS")) {
    exit("This file cannot be accessed directly");
}

/**
 * Security Pack — Time-Based Token (TOTP) provider.
 *
 * As of this version, the actual cryptographic math (secret generation,
 * HOTP/TOTP computation, code verification) is delegated to
 * robthree/twofactorauth (https://github.com/RobThree/TwoFactorAuth,
 * MIT licensed, vendored verbatim at
 * lib/Security/TwoFactor/vendor/robthree/twofactorauth/ — commit
 * 85408c4e775dba7c0802f2d928efd921d530bc5b, tag v3.0.3) rather than
 * this class's own hand-rolled implementation. RobThree/TwoFactorAuth
 * is the most widely used standalone PHP TOTP library (no framework
 * dependency, MIT license, actively maintained since 2014) — using it
 * here means the actual bit-twiddling that produces every login code
 * runs through code many other projects also depend on and have
 * exercised, rather than through logic unique to Security Pack. Only
 * the core, zero-dependency files were vendored (RobThree\Auth\
 * TwoFactorAuth, Algorithm, TwoFactorAuthException, the CSRNG/local-
 * time providers) — every QR-rendering provider (which needs extra
 * Composer packages, or — for the HTTP-based ones — sends the secret to
 * a third party) was deliberately left out; see NullQrCodeProvider's
 * docblock for why.
 *
 * This class is now a thin, STATIC, STATELESS adapter in front of that
 * library — every other file in Security Pack (TotpEnrollmentService,
 * tests) keeps calling the exact same static methods as before this
 * change, so this was a swap of the engine underneath an unchanged
 * public API, not a rewrite of every call site.
 *
 * Requires PHP >=8.2 (robthree/twofactorauth's own requirement) —
 * guarded explicitly in dct_totp_2fa_bootstrap()/security_pack.php
 * rather than left as an unclear fatal on an older host.
 *
 * Defaults are unchanged: HMAC-SHA1, 6 digits, 30-second period, +/-1
 * time-step clock tolerance — the same defaults every mainstream
 * authenticator app (Google Authenticator, Microsoft Authenticator,
 * Authy, or any other RFC-compliant authenticator app) already
 * implements, so enrollment works with an app the user already has
 * installed.
 */
class TotpService
{
    public const ALGORITHM = "sha1";
    public const DIGITS = 6;
    public const PERIOD_SECONDS = 30;
    public const CLOCK_TOLERANCE_STEPS = 1;
    public const SECRET_BYTES = 20; // 160 bits, matches RFC 4226's recommended HMAC-SHA1 key size

    private const BASE32_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";

    /**
     * Builds a short-lived RobThree\Auth\TwoFactorAuth instance for one
     * call. Construction is pure/cheap (no I/O) — a NullQrCodeProvider
     * satisfies the constructor's required QR provider without ever
     * being invoked (see that class's docblock).
     */
    private static function engine(
        int $period = self::PERIOD_SECONDS,
        int $digits = self::DIGITS,
        string $algorithm = self::ALGORITHM,
        ?string $issuer = null
    ): RobThreeTwoFactorAuth {
        return new RobThreeTwoFactorAuth(
            new NullQrCodeProvider(),
            $issuer,
            $digits,
            $period,
            RobThreeAlgorithm::from(strtolower($algorithm))
        );
    }

    /** Cryptographically random Base32 secret, generated by robthree/twofactorauth's CSRNGProvider (random_bytes() under the hood). */
    public static function generateSecret(int $bytes = self::SECRET_BYTES): string
    {
        return self::engine()->createSecret(max(10, $bytes) * 8);
    }

    public static function base32Encode(string $data): string
    {
        if($data === "") {
            return "";
        }
        $bits = "";
        foreach (str_split($data) as $char) {
            $bits .= str_pad(decbin(ord($char)), 8, "0", STR_PAD_LEFT);
        }
        $output = "";
        foreach (str_split($bits, 5) as $chunk) {
            if(strlen($chunk) < 5) {
                $chunk = str_pad($chunk, 5, "0", STR_PAD_RIGHT);
            }
            $output .= self::BASE32_ALPHABET[bindec($chunk)];
        }
        return $output;
    }

    public static function base32Decode(string $secret): string
    {
        $secret = strtoupper(preg_replace("/[^A-Z2-7]/i", "", $secret) ?? "");
        if($secret === "") {
            return "";
        }
        $bits = "";
        foreach (str_split($secret) as $char) {
            $pos = strpos(self::BASE32_ALPHABET, $char);
            if($pos === false) {
                continue;
            }
            $bits .= str_pad(decbin($pos), 5, "0", STR_PAD_LEFT);
        }
        $bytes = "";
        foreach (str_split($bits, 8) as $chunk) {
            if(strlen($chunk) < 8) {
                continue; // trailing padding bits, not a full byte
            }
            $bytes .= chr((int) bindec($chunk));
        }
        return $bytes;
    }

    /**
     * RFC 4226 HOTP value for a given counter, computed via
     * robthree/twofactorauth's getCode(). HOTP itself has no concept of
     * "period" (that's a TOTP-only idea layered on top), but the
     * library's public API only exposes a timestamp-based getCode() —
     * so a counter is converted to an equivalent timestamp
     * ($counter * $period) before delegating, and PERIOD_SECONDS
     * cancels out exactly in the library's own
     * floor(timestamp / period) = $counter recovery. Zero-padded
     * numeric string.
     */
    public static function hotp(string $secretBase32, int $counter, int $digits = self::DIGITS): string
    {
        return self::engine(self::PERIOD_SECONDS, $digits)->getCode($secretBase32, $counter * self::PERIOD_SECONDS);
    }

    /** RFC 6238 TOTP value at a given Unix timestamp. */
    public static function totpAt(string $secretBase32, int $timestamp, int $period = self::PERIOD_SECONDS, int $digits = self::DIGITS): string
    {
        return self::engine($period, $digits)->getCode($secretBase32, $timestamp);
    }

    /**
     * Verify a submitted code against the current time step, tolerating
     * clock drift of ±$toleranceSteps steps (Section 26 — do not
     * permanently lock the user out over a small clock drift).
     *
     * Defined in terms of {@see matchingStep()} — see that method's
     * docblock.
     *
     * @return bool
     */
    public static function verify(
        string $secretBase32,
        string $candidateCode,
        int $timestamp,
        int $toleranceSteps = self::CLOCK_TOLERANCE_STEPS,
        int $period = self::PERIOD_SECONDS,
        int $digits = self::DIGITS
    ): bool {
        return self::matchingStep($secretBase32, $candidateCode, $timestamp, $toleranceSteps, $period, $digits) !== null;
    }

    /**
     * Replay-protection primitive (rebuild requirement #11 — "prevents
     * OTP replay"). Uses robthree/twofactorauth's getCode() (the actual
     * HOTP/TOTP crypto primitive — HMAC + base32 decode) for every
     * candidate in the ±$toleranceSteps window, compared via this
     * class's own hash_equals() loop — deliberately NOT via the
     * library's own verifyCode() convenience wrapper. Confirmed via this
     * project's own RFC 6238/4226 test-vector tests: verifyCode()'s
     * `bool` + by-reference-`$timeslice` contract cannot distinguish "no
     * match" from "matched at counter 0" (both leave $timeslice at its
     * initial 0, and verifyCode() returns `$timeslice > 0`) — counter 0
     * only occurs at/before the Unix epoch and is never reachable with a
     * real wall-clock timestamp, so this is not a practical
     * vulnerability, but it IS a genuine correctness gap the RFC
     * 4226 Appendix D test vector (counter 0, secret
     * "12345678901234567890") caught directly. Looping over the
     * library's own getCode() sidesteps that boundary case entirely
     * while still delegating 100% of the actual cryptographic
     * computation to the vendored library — only the tolerance-window
     * iteration and the match decision are this class's own code, same
     * as before this class started using robthree/twofactorauth at all.
     *
     * The digit/format validation (exactly $digits numeric characters)
     * happens BEFORE the loop, to avoid unnecessary HMAC work for input
     * that can never match.
     *
     * WHY a counter and not a boolean: TOTP steps are monotonically
     * increasing with wall-clock time, so "the same counter (or an
     * earlier one) was already accepted for this account" is a complete,
     * standard replay check — see TotpEnrollmentService::verifyLogin()
     * for where this counter is compared against the account's stored
     * last_used_step and, on success, persisted.
     *
     * PURE — no I/O beyond the vendored library's own (also pure) HMAC
     * computation — so this is also what verify() itself delegates to.
     */
    public static function matchingStep(
        string $secretBase32,
        string $candidateCode,
        int $timestamp,
        int $toleranceSteps = self::CLOCK_TOLERANCE_STEPS,
        int $period = self::PERIOD_SECONDS,
        int $digits = self::DIGITS
    ): ?int {
        $candidateCode = preg_replace("/\s+/", "", $candidateCode) ?? "";
        if(!preg_match('/^\d{' . $digits . '}$/', $candidateCode)) {
            return null;
        }
        $engine = self::engine($period, $digits);
        for ($stepOffset = -$toleranceSteps; $stepOffset <= $toleranceSteps; $stepOffset++) {
            $checkTs = $timestamp + ($stepOffset * $period);
            if($checkTs < 0) {
                continue;
            }
            $counter = intdiv($checkTs, max(1, $period));
            $expected = $engine->getCode($secretBase32, $checkTs);
            if(hash_equals($expected, $candidateCode)) {
                return $counter;
            }
        }
        return null;
    }

    /**
     * otpauth:// provisioning URI (Section 13) for QR/manual entry,
     * built by robthree/twofactorauth's getQRText(). Authenticator apps
     * that support URI-scheme registration can open this link directly;
     * it also encodes everything a manual-entry flow needs (secret,
     * issuer, algorithm, digits, period).
     */
    public static function provisioningUri(string $secretBase32, string $accountLabel, string $issuer = "DCTLAB Security Pack"): string
    {
        return self::engine(issuer: $issuer)->getQRText($accountLabel, $secretBase32);
    }

    /** Cosmetic grouping of a Base32 secret into 4-character blocks for manual entry. Not part of robthree/twofactorauth — Security Pack's own display formatting. */
    public static function formatSecretForDisplay(string $secretBase32): string
    {
        return trim(chunk_split($secretBase32, 4, " "));
    }

    // --- Secret-at-rest encryption (Section 14) — unrelated to robthree/twofactorauth, Security Pack's own storage layer ---

    /**
     * Encrypt a TOTP secret for storage using libsodium's secretbox
     * (XSalsa20-Poly1305, PHP 7.2+ core extension — not a homegrown
     * primitive). $masterKey is a raw 32-byte key managed by the caller
     * (see TotpKeyStore) — never hard-coded, never exposed to clients.
     * Returns a self-contained base64 blob (nonce + ciphertext).
     */
    public static function encryptSecret(string $secretBase32, string $masterKey): string
    {
        if(!function_exists("sodium_crypto_secretbox") || strlen($masterKey) !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES) {
            throw new \RuntimeException("libsodium is unavailable or the master key is the wrong length — cannot safely encrypt the TOTP secret. Refusing to fall back to weak/no encryption.");
        }
        $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
        $cipher = sodium_crypto_secretbox($secretBase32, $nonce, $masterKey);
        return base64_encode($nonce . $cipher);
    }

    public static function decryptSecret(string $blob, string $masterKey): ?string
    {
        if(!function_exists("sodium_crypto_secretbox_open")) {
            return null;
        }
        $raw = base64_decode($blob, true);
        if($raw === false || strlen($raw) <= SODIUM_CRYPTO_SECRETBOX_NONCEBYTES) {
            return null;
        }
        $nonce = substr($raw, 0, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
        $cipher = substr($raw, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
        $plain = sodium_crypto_secretbox_open($cipher, $nonce, $masterKey);
        return $plain === false ? null : $plain;
    }
}
